import { resolve, join } from "path";
import { mkdirSync, existsSync } from "fs";
import { detectPlatform } from "../../lib/platform";
import { readFullConfig, expandHome } from "../../lib/config";
import { saveActivePrefix } from "../../lib/config";
import { buildXdgEnv } from "../../lib/env";
import { uvUrl, ripgrepUrl, opencodeUrl, installTool, installUvTools } from "../../lib/tools";
import { createWorkspaceScaffold, syncWorkspace, generateAgentsMd } from "../../lib/workspace";
import { bootstrapWithOpencode } from "../../lib/bootstrap";
import { WORKSPACE_PACKAGES } from "../../lib/constants";

export async function install(prefix: string): Promise<void> {
  prefix = resolve(prefix);
  console.log(`Installing nightshift tools to ${prefix}`);

  const platform = detectPlatform();
  console.log(`Detected platform: ${platform.os} / ${platform.arch}`);

  const uv = uvUrl(platform);
  await installTool("uv", uv.url, prefix, [
    { linkName: "uv", target: uv.extractedBinary },
  ]);

  const rg = ripgrepUrl(platform);
  await installTool("ripgrep", rg.url, prefix, [
    { linkName: "rg", target: rg.extractedBinary },
  ]);

  const oc = opencodeUrl(platform);
  await installTool("opencode", oc.url, prefix, [
    { linkName: "opencode", target: oc.extractedBinary },
  ]);

  await installUvTools(prefix);

  // Create workspace scaffold
  const config = await readFullConfig(process.cwd());
  const workspacePath = config?.workspacePath
    ? resolve(expandHome(config.workspacePath))
    : join(prefix, "workspace");
  const libraryName = config?.libraryName ?? "agent_lib";
  const packages = config?.workspacePackages ?? WORKSPACE_PACKAGES;

  // Create XDG directories for isolated opencode config/data/cache/state
  const xdgDirs = ["config", "share", "cache", "state"];
  for (const dir of xdgDirs) {
    mkdirSync(join(prefix, dir), { recursive: true });
  }

  const xdgEnv = buildXdgEnv(prefix);

  const isNewWorkspace = !existsSync(workspacePath);

  if (isNewWorkspace) {
    // Create scaffold without AGENTS.md - that will be generated by opencode
    await createWorkspaceScaffold(workspacePath, libraryName, packages, { skipAgentsMd: true });
    await syncWorkspace(prefix, workspacePath);

    const { runBootstrapPrompt } = await import("../../bootstrap-prompt");

    try {
      const result = await runBootstrapPrompt(
        async (userIntent, ui, client, serverUrl, model) => {
          await bootstrapWithOpencode(prefix, workspacePath, userIntent, xdgEnv, ui, client, serverUrl, model);
        },
        {
          prefix,
          workspacePath,
          xdgEnv,
        }
      );

      if (!result) {
        // User skipped (Ctrl+C)
        console.log("\nSkipped bootstrap. Using default AGENTS.md.");
        await Bun.write(join(workspacePath, "AGENTS.md"), generateAgentsMd(libraryName));
      } else {
        // Kill the server process after bootstrap
        result.serverProc.kill();
      }
    } catch (err) {
      console.error("\nBootstrap failed:", err);
      console.log("Falling back to default AGENTS.md.");
      await Bun.write(join(workspacePath, "AGENTS.md"), generateAgentsMd(libraryName));
    }
  } else {
    console.log(`\nWorkspace already exists at ${workspacePath}`);
  }

  // Save active prefix for future runs
  await saveActivePrefix(prefix);

  console.log("\nInstallation complete!");
  console.log(`  Prefix: ${prefix}`);
  console.log(`  Workspace: ${workspacePath}`);
  console.log(`  Run: nightshift run`);
}
